# Generated by Django 5.2 on 2025-04-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='tipo',
            field=models.CharField(choices=[('sitio_web', 'Sitio Web'), ('correo', 'Correo Electrónico'), ('banco', 'Banco'), ('aplicacion', 'Aplicación'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
